### ISSUE TITLE
chart images.zip is corrupted can't be unzipped

### ISSUE THREAD

**Issue by moured** [pranonrahman/ChartSumm#2]
Dear Authors, 

Thanks for your contribution. The drive file "chart images.zip" is **corrupted and can't be unzipped**. I have tested with different machines. [ [drive link ](https://drive.google.com/drive/folders/1HPsFUojoHctFD2AGuotRPKRz-o0jXfRJ) ] 

Can you please re-upload it? 

Best,

**Comment by whitesockcat** [comment]
+1

**Comment by whitesockcat** [comment]
7z ok for me

**Comment by pranonrahman** [comment]
@whitesockcat @moured , i downloaded and extracted the files and it worked fine. Please try again. Thank you
